//THIS PROGRAM IS CREATED BY BHAVIN_ONDHIYA
ANS-1
import java.util.*;
public class prac4_1 
{ 
    static public void main(String[] args) 
    { Scanner sc=new Scanner(System.in);
       System.out.println("Give the number which you want to divide with 0"); 
         int a=sc.nextInt(); 
         try 
            { 
                System.out.println(a/0); 
            } 
        catch (Exception e) 
        { 
            System.out.println("The division of any number with zero is not possible");
        }
    }
}


ANS-2
//THIS PROGRAM IS CREATED BY BHAVIN_ONDHIYA
import java.util.*; 
class check extends Exception 
{ public check(String s)
 { super(s); 
}
 }
 class Prac4_2 { 
class demo
 { static void f_(int a,int b)throws check
 { 
   throw new check("There is an Exception");
 }
 }
 public static void main(String[] args) 
{ 
try {
 demo.f_(4,8); 
} 
catch (check e) {
 System.out.println(e); 
}

}
 }
 
 
 
 ANS-3
 //THIS PROGRAM IS CREATED BY BHAVIN_ONDHIYA
import java.util.*; 
public class Prac4_3 
{ 
    public static void main(String[] args) 
    { 
     Scanner sc=new Scanner(System.in);
     int n;
     System.out.println("If you want arithmatic exception the press 1 or arrey index out of bound exception then 2"); 
    n=sc.nextInt(); 
          try
          { 
             if (n==1) 
             { 
                System.out.println(1/0); 
             } 
             if(n==2)
             { int a[]=new int[3];
                for(int i=0;i<=3;i++) 
                {
                    a[i]=sc.nextInt();
                }
             }
           } 
        catch(ArithmeticException e) 
            {
                System.out.println("There is an Arithmatic Exception");
            } 
        catch (ArrayIndexOutOfBoundsException e) 
            { 
                System.out.println("THere is ArreyIndexOutOfBound Exception");
            }
        finally 
            { 
                System.out.println("We found an Exception");
            }
    }

